//! Chat generation loop (worker side) + streaming events.
//! OPENAI-CHAT-API-PLAN.md §Streaming, §Slot Management, Implementation Plan
//! Phase 3/4: serial execution on a dedicated worker thread; per-request
//! `tokio::sync::mpsc` channels give natural backpressure; UTF-8-safe
//! incremental decoding and stop-string truncation happen here, before any
//! chunk is emitted.

use rand::SeedableRng;
use tokio::sync::mpsc;

use crate::graph::cache::GraphCache;
use crate::models::{ModelDef, SpecialTokens};
use crate::server::slot::{Slot, SlotState};
use crate::server::types::{ApiError, SamplingParams};
use crate::tokenizer::Tokenizer;

/// Per-request event stream pushed by the worker to the HTTP handler.
pub enum StreamEvent {
    /// A UTF-8-safe text chunk (never ends mid-character).
    Text(String),
    /// Generation finished: reason is "stop" or "length"; `tokens` is the
    /// exact completion-token count (for `usage`).
    Finish { reason: String, tokens: usize },
    /// Terminal error (ApiError carries status/type for the HTTP response).
    Err(ApiError),
}

/// One queued inference task. `input_ids` is the rendered+tokenized prompt
/// (the handler tokenizes so context-overflow checks happen before queuing).
pub struct Job {
    pub input_ids: Vec<u32>,
    pub params: SamplingParams,
    pub tx: mpsc::Sender<StreamEvent>,
}

fn is_stop_token(id: u32, special: &SpecialTokens) -> bool {
    id == special.eos || Some(id) == special.im_end
}

/// Run one job on `slot` to completion, pushing events into `job.tx`.
///
/// Termination: EOS / im_end -> "stop"; stop string -> "stop" (truncated);
/// `max_tokens` or slot context full -> "length". The slot's `GraphCache` is
/// passed by the caller and is only ever touched here (serial worker), so KV
/// isolation is structural. The generated text/usage travels over the event
/// channel; this function only reports errors.
pub fn generate(
    model: &dyn ModelDef,
    tokenizer: &Tokenizer,
    cache: &mut GraphCache,
    n_ctx_slot: usize,
    input_ids: &[u32],
    params: &SamplingParams,
    tx: &mpsc::Sender<StreamEvent>,
) -> Result<(), ApiError> {
    if input_ids.is_empty() {
        return Err(ApiError::invalid_request("prompt tokenizes to nothing"));
    }
    if input_ids.len() > n_ctx_slot {
        return Err(ApiError::exceed_context(format!(
            "prompt of {} tokens exceeds slot context of {}",
            input_ids.len(),
            n_ctx_slot
        )));
    }

    let nt = input_ids.len();
    let positions: Vec<usize> = (0..nt).collect();
    let special = model.special_tokens();

    // Prefill (n_out=1: only the last token's logits are returned).
    let last_logits = guarded_forward(model, input_ids, &positions, nt, n_ctx_slot, cache)?;
    let mut logits = last_logits;
    let mut current_pos = nt;

    let mut rng = rand::rngs::StdRng::seed_from_u64(params.seed);
    const REPEAT_LAST_N: usize = 64;
    let mut prev_tokens = sampler_recent_window(input_ids, REPEAT_LAST_N);

    let stop_bytes: Vec<Vec<u8>> = params
        .stop_strings
        .iter()
        .map(|s| s.as_bytes().to_vec())
        .collect();
    let stop_refs: Vec<&[u8]> = stop_bytes.iter().map(|v| v.as_slice()).collect();

    // `full` accumulates ALL generated bytes; `emitted` tracks how many of them
    // were already sent as Text events. Stop detection runs on `full` (llama.cpp
    // checks the whole generated text, so a stop string split across tokens is
    // caught even though its earlier tokens were already emitted — they are
    // simply left in the client's buffer, exactly like llama.cpp).
    let mut full: Vec<u8> = Vec::new();
    let mut emitted: usize = 0;
    let mut completion_tokens = 0usize;
    let mut finish_reason = "stop";
    let mut stopped_by_string = false;

    // Emit `full[emitted..end]` as one Text event (complete UTF-8 by caller).
    let mut emit = |full: &[u8], emitted: usize, end: usize, tx: &mpsc::Sender<StreamEvent>| -> Result<(), ApiError> {
        if end > emitted {
            let chunk = String::from_utf8_lossy(&full[emitted..end]).into_owned();
            if tx.blocking_send(StreamEvent::Text(chunk)).is_err() {
                return Err(ApiError::server("client disconnected"));
            }
        }
        Ok(())
    };

    loop {
        // max_tokens limit
        if params.max_tokens >= 0 && completion_tokens as i64 >= params.max_tokens {
            finish_reason = "length";
            break;
        }
        // slot context full (KV write positions must stay < n_ctx_slot)
        if current_pos >= n_ctx_slot {
            finish_reason = "length";
            break;
        }

        let sampled = crate::sampler::sample_with_penalties(
            &mut logits,
            params.temp,
            params.top_k,
            params.top_p,
            params.repeat_penalty,
            params.frequency_penalty,
            params.presence_penalty,
            &prev_tokens,
            &mut rng,
        );
        if is_stop_token(sampled.token_id, &special) {
            finish_reason = "stop";
            break;
        }
        completion_tokens += 1;
        prev_tokens.push(sampled.token_id);
        if prev_tokens.len() > REPEAT_LAST_N {
            prev_tokens.drain(0..prev_tokens.len() - REPEAT_LAST_N);
        }

        // Stop-string detection on the FULL byte stream before emitting.
        full.extend_from_slice(&tokenizer.decode_bytes(&[sampled.token_id]));
        if let Some(cut) = crate::sampler::match_stop_suffix(&full, &stop_refs) {
            stopped_by_string = true;
            // Truncate at the stop string. If the stop's start lies before the
            // already-emitted bytes, the emitted prefix stays (unavoidable);
            // otherwise emit the untruncated tail up to `cut`.
            if cut > emitted {
                emit(&full, emitted, cut, tx)?;
                emitted = cut;
            }
            break;
        }

        // Emit only the complete-UTF-8 prefix; hold back a split multi-byte char.
        let complete = emitted + crate::tokenizer::complete_utf8_prefix_len(&full[emitted..]);
        if complete > emitted {
            emit(&full, emitted, complete, tx)?;
            emitted = complete;
        }

        // Decode step.
        logits = guarded_forward(
            model,
            &[sampled.token_id],
            &[current_pos],
            1,
            n_ctx_slot,
            cache,
        )?;
        current_pos += 1;
    }

    // Final flush: everything after `emitted` — but if we stopped on a stop
    // string, nothing beyond `cut` (== full.len() after truncation below) may
    // leak; truncating `full` to `cut` makes the flush safe in both cases.
    if stopped_by_string {
        // `full` still holds bytes past the stop; drop them.
        if emitted < full.len() {
            // cut was captured above; recompute it the same way.
            if let Some(cut) = crate::sampler::match_stop_suffix(&full, &stop_refs) {
                full.truncate(cut);
            }
            if emitted < full.len() {
                emit(&full, emitted, full.len(), tx)?;
            }
        }
    } else if emitted < full.len() {
        emit(&full, emitted, full.len(), tx)?;
    }
    let _ = tx
        .blocking_send(StreamEvent::Finish { reason: finish_reason.to_string(), tokens: completion_tokens });

    Ok(())
}

/// `forward_graph_cached` wrapped so an unexpected panic (e.g. an internal
/// invariant) becomes a 500 instead of killing the worker thread.
fn guarded_forward(
    model: &dyn ModelDef,
    tokens: &[u32],
    positions: &[usize],
    n_out: usize,
    n_ctx: usize,
    cache: &mut GraphCache,
) -> Result<Vec<f32>, ApiError> {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        model.forward_graph_cached(tokens, positions, n_out, n_ctx, cache)
    }))
    .map_err(|_| ApiError::server("inference panicked"))
}

/// Worker thread: drains the job queue serially, one slot at a time.
/// Busy slots defer naturally — the queue is unbounded (llama.cpp semantics).
pub fn worker_loop(
    model: Box<dyn ModelDef>,
    tokenizer: Tokenizer,
    mut slots: Vec<Slot>,
    mut job_rx: mpsc::Receiver<Job>,
) {
    loop {
        let Some(job) = job_rx.blocking_recv() else {
            break; // all senders dropped: server shutting down
        };
        let Some(slot) = slots.iter_mut().find(|s| s.state == SlotState::Idle) else {
            let _ = job
                .tx
                .blocking_send(StreamEvent::Err(ApiError::unavailable("no idle slot")));
            continue;
        };
        slot.state = SlotState::Processing;
        let result = generate(
            &*model,
            &tokenizer,
            &mut slot.cache,
            slot.n_ctx_slot,
            &job.input_ids,
            &job.params,
            &job.tx,
        );
        if let Err(e) = result {
            let _ = job.tx.blocking_send(StreamEvent::Err(e));
        }
        slot.state = SlotState::Idle;
    }
}

fn sampler_recent_window(tokens: &[u32], last_n: usize) -> Vec<u32> {
    crate::sampler::recent_window(tokens, last_n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stop_token_matches_eos_and_im_end() {
        let special = SpecialTokens { eos: 2, im_end: Some(7) };
        assert!(is_stop_token(2, &special));
        assert!(is_stop_token(7, &special));
        assert!(!is_stop_token(3, &special));
    }
}
